# Semantic Release Configuration
branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  # Analyze commits with conventional-changelog
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
      releaseRules:
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
        - type: "perf"
          release: "patch"
        - type: "revert"
          release: "patch"
        - type: "docs"
          scope: "README"
          release: "patch"
        - type: "style"
          release: false
        - type: "chore"
          release: false
        - type: "refactor"
          release: false
        - type: "test"
          release: false
        - type: "build"
          release: false
        - type: "ci"
          release: false
        - breaking: true
          release: "major"
        - revert: true
          release: "patch"
      parserOpts:
        noteKeywords:
          - "BREAKING CHANGE"
          - "BREAKING CHANGES"
          - "BREAKING"

  # Generate release notes
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: "feat"
            section: "Features"
            hidden: false
          - type: "fix"
            section: "Bug Fixes"
            hidden: false
          - type: "perf"
            section: "Performance Improvements"
            hidden: false
          - type: "revert"
            section: "Reverts"
            hidden: false
          - type: "docs"
            section: "Documentation"
            hidden: false
          - type: "style"
            section: "Styles"
            hidden: true
          - type: "chore"
            section: "Miscellaneous Chores"
            hidden: true
          - type: "refactor"
            section: "Code Refactoring"
            hidden: true
          - type: "test"
            section: "Tests"
            hidden: true
          - type: "build"
            section: "Build System"
            hidden: true
          - type: "ci"
            section: "Continuous Integration"
            hidden: true

  # Update CHANGELOG.md
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."

  # Update version in Cargo.toml
  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i 's/^version = ".*"/version = "${nextRelease.version}"/' Cargo.toml
        cargo check
      publishCmd: "echo 'Version ${nextRelease.version} prepared'"

  # Commit release assets
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "Cargo.toml"
        - "Cargo.lock"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  # Create GitHub release
  - - "@semantic-release/github"
    - assets:
        - path: "target/release/netrain"
          name: "netrain-linux-amd64"
          label: "Linux AMD64 binary"