//! Golden tests: real pcap fixtures replayed through the full pipeline.
//!
//! The fixtures in `tests/fixtures/` are generated by the builders below, so
//! they are reviewable as code. `fixtures_match_their_generators` fails if a
//! file on disk drifts from its builder; regenerate with
//! `NETRAIN_REGEN_FIXTURES=1 cargo test --test replay_golden`.

use std::path::PathBuf;
use std::process::Command;

use netrain::decode::TcpFlags;
use netrain::pcapfile::{PcapReader, PcapWriter};
use netrain::replay::analyze_pcap;
use netrain::synth::{dns_query, eth_tcp, eth_udp, ethernet, ipv4, ipv6, tcp, udp, with_vlan};
use netrain::{Protocol, ThreatLevel};

const T0: i64 = 1_700_000_000_000_000;
const CLIENT: [u8; 4] = [192, 168, 1, 10];
const SERVER: [u8; 4] = [93, 184, 216, 34];
const RESOLVER: [u8; 4] = [9, 9, 9, 9];
const SYN: u8 = TcpFlags::SYN;
const ACK: u8 = TcpFlags::ACK;
const PSH_ACK: u8 = TcpFlags::PSH | TcpFlags::ACK;

/// An ordinary browsing session: DNS, a TLS connection, plain HTTP, SSH.
fn normal_traffic() -> Vec<u8> {
    let tls_hello = [0x16, 0x03, 0x01, 0x00, 0x05, 0x01, 0x00, 0x00, 0x01, 0x00];
    let mut w = PcapWriter::new(1);
    let mut t = T0;
    let mut add = |frame: Vec<u8>| {
        w.packet(t, &frame);
        t += 40_000;
    };
    add(eth_udp(CLIENT, RESOLVER, 53001, 53, &dns_query("example.com")));
    add(eth_udp(RESOLVER, CLIENT, 53, 53001, &dns_query("example.com")));
    add(eth_tcp(CLIENT, SERVER, 50001, 443, SYN, b""));
    add(eth_tcp(SERVER, CLIENT, 443, 50001, SYN | ACK, b""));
    add(eth_tcp(CLIENT, SERVER, 50001, 443, ACK, b""));
    add(eth_tcp(CLIENT, SERVER, 50001, 443, PSH_ACK, &tls_hello));
    add(eth_tcp(SERVER, CLIENT, 443, 50001, PSH_ACK, &[0x17, 0x03, 0x03, 0x00, 0x02, 0xaa, 0xbb]));
    add(eth_tcp(CLIENT, SERVER, 50002, 80, SYN, b""));
    add(eth_tcp(SERVER, CLIENT, 80, 50002, SYN | ACK, b""));
    add(eth_tcp(CLIENT, SERVER, 50002, 80, PSH_ACK, b"GET / HTTP/1.1\r\nHost: example.com\r\n\r\n"));
    add(eth_tcp(SERVER, CLIENT, 80, 50002, PSH_ACK, b"HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n"));
    add(eth_tcp(CLIENT, [192, 168, 1, 20], 50003, 22, SYN, b""));
    add(eth_tcp([192, 168, 1, 20], CLIENT, 22, 50003, PSH_ACK, b"SSH-2.0-OpenSSH_9.6\r\n"));
    w.finish()
}

/// One host probing 40 ports on another within two seconds.
fn port_scan() -> Vec<u8> {
    let mut w = PcapWriter::new(1);
    for port in 1..=40u16 {
        let frame = eth_tcp([203, 0, 113, 7], [10, 0, 0, 1], 40000, port, SYN, b"");
        w.packet(T0 + i64::from(port) * 50_000, &frame);
    }
    w.finish()
}

/// 150 spoofed sources sending SYNs to one web server; nothing is answered.
fn ddos_attack() -> Vec<u8> {
    let mut w = PcapWriter::new(1);
    for i in 0..150u32 {
        let src = [198, 51, (i / 250) as u8, (i % 250) as u8 + 1];
        let frame = eth_tcp(src, [10, 0, 0, 80], 1024 + i as u16, 80, SYN, b"");
        w.packet(T0 + i64::from(i) * 10_000, &frame);
    }
    w.finish()
}

/// One of everything the decoder handles, plus things it must skip.
fn mixed_protocols() -> Vec<u8> {
    let mut v6_src = [0u8; 16];
    v6_src[..2].copy_from_slice(&[0x20, 0x01]);
    v6_src[15] = 1;
    let mut v6_dst = [0u8; 16];
    v6_dst[..2].copy_from_slice(&[0x20, 0x01]);
    v6_dst[15] = 2;

    let mut w = PcapWriter::new(1);
    let mut t = T0;
    let mut add = |frame: Vec<u8>| {
        w.packet(t, &frame);
        t += 100_000;
    };
    add(eth_tcp(CLIENT, SERVER, 50001, 5432, PSH_ACK, b"\x00\x00\x00\x08")); // TCP
    add(eth_udp(CLIENT, SERVER, 50002, 123, &[0x1b; 48])); // UDP (NTP)
    add(eth_udp(CLIENT, RESOLVER, 50003, 53, &dns_query("rust-lang.org"))); // DNS
    add(eth_tcp(CLIENT, SERVER, 50004, 8080, PSH_ACK, b"POST /api HTTP/1.1\r\n\r\n")); // HTTP off-port
    add(eth_tcp(CLIENT, SERVER, 50005, 443, SYN, b"")); // HTTPS by port
    add(eth_tcp(CLIENT, SERVER, 50006, 2222, PSH_ACK, b"SSH-2.0-test\r\n")); // SSH off-port
    add(ethernet(0x86dd, &ipv6(17, v6_src, v6_dst, &udp(50007, 53, &dns_query("ipv6.example"))))); // DNS over IPv6
    add(ethernet(0x86dd, &ipv6(6, v6_src, v6_dst, &tcp(50008, 443, SYN, b"")))); // HTTPS over IPv6
    add(with_vlan(&eth_tcp(CLIENT, SERVER, 50009, 80, SYN, b""), 42)); // HTTP inside a VLAN
    add(ethernet(0x0806, &[0u8; 28])); // ARP: not IP
    add(vec![0xde, 0xad, 0xbe, 0xef]); // runt frame
    add(ethernet(0x0800, &ipv4(1, CLIENT, SERVER, &[8, 0, 0, 0, 0, 1, 0, 1]))); // ICMP echo
    w.finish()
}

fn fixtures() -> [(&'static str, Vec<u8>); 4] {
    [
        ("normal_traffic.pcap", normal_traffic()),
        ("port_scan.pcap", port_scan()),
        ("ddos_attack.pcap", ddos_attack()),
        ("mixed_protocols.pcap", mixed_protocols()),
    ]
}

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures").join(name)
}

fn load(name: &str) -> Vec<u8> {
    std::fs::read(fixture_path(name)).unwrap_or_else(|e| panic!("cannot read fixture {name}: {e}"))
}

#[test]
fn fixtures_match_their_generators() {
    let regenerate = std::env::var_os("NETRAIN_REGEN_FIXTURES").is_some();
    for (name, bytes) in fixtures() {
        if regenerate {
            std::fs::write(fixture_path(name), &bytes).unwrap();
        }
        assert!(
            load(name) == bytes,
            "{name} differs from its generator; run with NETRAIN_REGEN_FIXTURES=1 to rewrite it"
        );
    }
}

#[test]
fn fixtures_are_valid_pcap_files() {
    for (name, _) in fixtures() {
        let file = load(name);
        let reader = PcapReader::new(&file).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(reader.link_type, 1, "{name} is Ethernet");
        for record in reader {
            record.unwrap_or_else(|e| panic!("{name}: {e}"));
        }
    }
}

#[test]
fn normal_traffic_is_classified_and_raises_nothing() {
    let s = analyze_pcap(&load("normal_traffic.pcap")).unwrap();
    assert_eq!(s.packets, 13);
    assert_eq!(s.undecodable, 0);
    assert_eq!(s.count(Protocol::DNS), 2);
    assert_eq!(s.count(Protocol::HTTPS), 5);
    assert_eq!(s.count(Protocol::HTTP), 4);
    assert_eq!(s.count(Protocol::SSH), 2);
    assert_eq!(s.count(Protocol::TCP) + s.count(Protocol::UDP) + s.count(Protocol::Unknown), 0);
    assert!(s.alerts.is_empty(), "false positive on ordinary traffic: {:?}", s.alerts);
    assert_eq!(s.peak(), ThreatLevel::Low);
}

#[test]
fn port_scan_is_detected_with_source_and_target() {
    let s = analyze_pcap(&load("port_scan.pcap")).unwrap();
    assert_eq!(s.packets, 40);
    assert_eq!(s.alerts.iter().collect::<Vec<_>>(), ["Port scan 203.0.113.7 -> 10.0.0.1"]);
    assert_eq!(s.peak(), ThreatLevel::High);
}

#[test]
fn syn_flood_is_detected_on_the_victim() {
    let s = analyze_pcap(&load("ddos_attack.pcap")).unwrap();
    assert_eq!(s.packets, 150);
    assert_eq!(s.count(Protocol::HTTP), 150);
    assert_eq!(s.alerts.iter().collect::<Vec<_>>(), ["SYN flood on 10.0.0.80"]);
    assert_eq!(s.peak(), ThreatLevel::Critical);
}

#[test]
fn mixed_protocols_cover_ipv6_vlan_and_skip_non_ip() {
    let s = analyze_pcap(&load("mixed_protocols.pcap")).unwrap();
    assert_eq!(s.packets, 10);
    assert_eq!(s.undecodable, 2, "ARP and the runt frame");
    assert_eq!(s.count(Protocol::TCP), 1);
    assert_eq!(s.count(Protocol::UDP), 1);
    assert_eq!(s.count(Protocol::DNS), 2, "IPv4 and IPv6");
    assert_eq!(s.count(Protocol::HTTP), 2, "off-port by payload, and inside a VLAN");
    assert_eq!(s.count(Protocol::HTTPS), 2, "IPv4 and IPv6");
    assert_eq!(s.count(Protocol::SSH), 1);
    assert_eq!(s.count(Protocol::Unknown), 1, "ICMP");
    assert!(s.alerts.is_empty());
}

/// The binary, reading through libpcap, must agree with the pure-Rust path.
#[test]
fn binary_summary_matches_library_analysis() {
    for (name, _) in fixtures() {
        let path = fixture_path(name);
        let out = Command::new(env!("CARGO_BIN_EXE_netrain"))
            .args(["--read", path.to_str().unwrap(), "--summary"])
            .output()
            .unwrap();
        assert!(out.status.success(), "{name}: {}", String::from_utf8_lossy(&out.stderr));
        let printed = String::from_utf8_lossy(&out.stdout);
        let mut expected = analyze_pcap(&load(name)).unwrap();
        // The default kernel filter (`ip or ip6`) removes non-IP frames
        // before netrain sees them, so they are not counted as undecodable.
        expected.undecodable = 0;
        assert_eq!(printed, expected.to_string(), "{name}");
    }
}

#[test]
fn binary_summary_honours_the_filter() {
    let path = fixture_path("mixed_protocols.pcap");
    let out = Command::new(env!("CARGO_BIN_EXE_netrain"))
        .args(["--read", path.to_str().unwrap(), "--summary", "--filter", "udp port 53"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let printed = String::from_utf8_lossy(&out.stdout);
    assert!(printed.contains("packets:      2"), "{printed}");
    assert!(printed.contains("  DNS   2"), "{printed}");
}
